CREATE TABLE IF NOT EXISTS `#__irvas_contacts` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`title` varchar(250) NOT NULL DEFAULT '',
`name` varchar(255) NOT NULL DEFAULT '',
`company_address` varchar(100) NOT NULL DEFAULT '',
`company_phone` varchar(20) NOT NULL DEFAULT '',
`company_fax` varchar(20) NOT NULL DEFAULT '',
`company_mobile` varchar(20) NOT NULL DEFAULT '',
`company_email` varchar(20) NOT NULL DEFAULT '',
`company_website` varchar(50) NOT NULL DEFAULT '',
`company_logo` varchar(50) NOT NULL DEFAULT '',
`company_vat` varchar(20) NOT NULL DEFAULT '',
`company_id` varchar(20) NOT NULL DEFAULT '',
`company_bank_acc` varchar(20) NOT NULL DEFAULT '',
`person_name` varchar(25) NOT NULL DEFAULT '',
`person_position` varchar(25) NOT NULL DEFAULT '',
`person_phone` varchar(20) NOT NULL DEFAULT '',
`person_email` varchar(20) NOT NULL DEFAULT '',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;